"""schema inicial — o que já existia antes do Alembic

Esta migração descreve o banco COMO ELE JÁ ERA quando o Alembic entrou. Num
banco novo ela cria tudo; num banco que já existe (o de desenvolvimento, e o de
qualquer instalação anterior) ela é apenas carimbada, nunca executada — ver
`app/db_migrations.py`, que detecta esse caso no startup e carimba sozinho.

Separá-la do delta de usuários (0002) é o que torna esse carimbo possível: se
`users` estivesse aqui dentro, carimbar o banco antigo pularia a criação dela.

Revision ID: 0001_schema_inicial
Revises:
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0001_schema_inicial"
down_revision: Union[str, None] = None
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_examples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('clip_path', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_title', sa.String(), nullable=True),
    sa.Column('source_channel', sa.String(), nullable=True),
    sa.Column('source_duration', sa.Float(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('source_start', sa.Float(), nullable=True),
    sa.Column('source_end', sa.Float(), nullable=True),
    sa.Column('alignment_confidence', sa.Float(), nullable=True),
    sa.Column('clip_duration', sa.Float(), nullable=True),
    sa.Column('analysis_json', sa.Text(), nullable=True),
    sa.Column('forensics_json', sa.Text(), nullable=True),
    sa.Column('opening_phrase', sa.String(), nullable=True),
    sa.Column('transcript_excerpt', sa.Text(), nullable=True),
    sa.Column('performance', sa.String(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('published', sa.Integer(), nullable=True),
    sa.Column('example_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_enhance_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('source_video_path', sa.String(), nullable=False),
    sa.Column('final_video_path', sa.String(), nullable=True),
    sa.Column('source_summary', sa.String(), nullable=True),
    sa.Column('final_summary', sa.String(), nullable=True),
    sa.Column('steps_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('status_detail', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('youtube_url', sa.String(), nullable=False),
    sa.Column('video_title', sa.String(), nullable=True),
    sa.Column('channel_name', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('video_path', sa.String(), nullable=True),
    sa.Column('audio_path', sa.String(), nullable=True),
    sa.Column('subtitle_mode', sa.String(), nullable=True),
    sa.Column('layout_mode', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('clip_mode', sa.String(), nullable=True),
    sa.Column('manual_clips', sa.Text(), nullable=True),
    sa.Column('manual_mode', sa.String(), nullable=True),
    sa.Column('facecam_rect', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('result_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('clips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('virality_score', sa.Float(), nullable=False),
    sa.Column('hook_score', sa.Float(), nullable=True),
    sa.Column('retention_score', sa.Float(), nullable=True),
    sa.Column('shareability_score', sa.Float(), nullable=True),
    sa.Column('loopability_score', sa.Float(), nullable=True),
    sa.Column('comment_bait_score', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('weak_points_json', sa.String(), nullable=True),
    sa.Column('trim_reason', sa.String(), nullable=True),
    sa.Column('segments_json', sa.Text(), nullable=True),
    sa.Column('hook', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('tags_json', sa.String(), nullable=True),
    sa.Column('suggested_title', sa.String(), nullable=True),
    sa.Column('transcript_excerpt', sa.Text(), nullable=True),
    sa.Column('part_number', sa.Integer(), nullable=True),
    sa.Column('parent_clip_id', sa.String(), nullable=True),
    sa.Column('subtitle_mode', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('metrics_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcripts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('words_json_path', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcripts')
    op.drop_table('clips')

    op.drop_table('jobs')
    op.drop_table('video_enhance_jobs')

    op.drop_table('reference_examples')
    # ### end Alembic commands ###
